# Comments 1111111111111111

trigger:
- master
pool:
  vmImage: ubuntu-latest

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: stage1
  displayName: Build image
  jobs:
  - job: job1_s1
    displayName: job1-s1
    steps:  
    - script: echo "task1-job1-s1"

